/**
 * TLS for the LAN surface.
 *
 * Bearer tokens over plain HTTP on a home network are readable by anything on
 * that network, which has been the honest caveat on the API since it existed.
 * The usual answer is a real certificate, which needs a domain and a renewal
 * story that a box in a closet does not have.
 *
 * The answer that actually fits: a self-signed certificate, plus certificate
 * pinning at pairing time. Pairing happens in person, on your own network, with
 * a code read off the box. That is exactly the setting where trust-on-first-use
 * is legitimate, and it is the same model SSH has used for thirty years.
 *
 * Generated by shelling out to openssl, which is present on macOS and every
 * Linux distribution, rather than taking a dependency to do it in process.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";
import { harborHome } from "./paths.js";

export interface TlsMaterial {
  readonly key: string;
  readonly cert: string;
  /** SHA-256 of the DER certificate, colon separated. What a client pins. */
  readonly fingerprint: string;
}

function tlsDir(): string {
  const dir = join(harborHome(), "tls");

  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true, mode: 0o700 });
  }

  return dir;
}

function fingerprintOf(certPath: string): string {
  const output = execFileSync("openssl", ["x509", "-in", certPath, "-noout", "-fingerprint", "-sha256"], {
    encoding: "utf8",
  });

  return (/=([0-9A-F:]+)/i.exec(output)?.[1] ?? "").trim();
}

/**
 * Loads the certificate, generating one on first use.
 *
 * Ten years, because rotating a pinned self-signed certificate means re-pairing
 * every device, and an annual re-pair is a chore nobody would do.
 */
export function ensureTls(hostnames: readonly string[] = []): TlsMaterial {
  const dir = tlsDir();
  const keyPath = join(dir, "harbor.key");
  const certPath = join(dir, "harbor.crt");

  if (!existsSync(keyPath) || !existsSync(certPath)) {
    const names = ["localhost", "harbor.local", ...hostnames];

    const alt = [
      ...names.map((name) => `DNS:${name}`),
      "IP:127.0.0.1",
      "IP:0.0.0.0",
    ].join(",");

    execFileSync(
      "openssl",
      [
        "req",
        "-x509",
        "-newkey",
        "rsa:2048",
        "-nodes",
        "-keyout",
        keyPath,
        "-out",
        certPath,
        "-days",
        "3650",
        "-subj",
        "/CN=harbor.local/O=Harbor",
        "-addext",
        `subjectAltName=${alt}`,
      ],
      { stdio: "pipe" },
    );
  }

  return {
    key: readFileSync(keyPath, "utf8"),
    cert: readFileSync(certPath, "utf8"),
    fingerprint: fingerprintOf(certPath),
  };
}

export function tlsAvailable(): boolean {
  try {
    execFileSync("openssl", ["version"], { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

/** Fingerprint of an already-generated certificate, without loading the key. */
export function currentFingerprint(): string | null {
  const certPath = join(tlsDir(), "harbor.crt");

  if (!existsSync(certPath)) {
    return null;
  }

  try {
    return fingerprintOf(certPath);
  } catch {
    // Fall back to computing it ourselves rather than failing a status call.
    const pem = readFileSync(certPath, "utf8");
    const der = Buffer.from(
      pem.replace(/-----(BEGIN|END) CERTIFICATE-----/g, "").replace(/\s+/g, ""),
      "base64",
    );

    return (createHash("sha256").update(der).digest("hex").toUpperCase().match(/../g) ?? []).join(":");
  }
}
